version: "3"
services:
  mondial_db:
    container_name: mondial_db
    image: postgres
    restart: always
    environment:
      #Change this password
      POSTGRES_PASSWORD: MRYJDYMOVAOFBBVF
    volumes:
      - ./init_db/postgres:/docker-entrypoint-initdb.d:ro
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile_hidden_from_binder
    container_name: jupyter
    ports:
    - 8888:8888
    volumes:
    - ./notebooks:/notebooks
    environment:
      PGHOST: mondial_db
      PGUSER: postgres
      PGPASSWORD: MRYJDYMOVAOFBBVF